
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// datasource.url here is required by prisma.config.ts (removing it entirely
// breaks the CLI), but this config only supports a single URL — no
// directUrl. It's used for the schema-engine's own preflight/CLI
// operations (migrate, studio), not by the app's actual Prisma Client at
// runtime (that reads schema.prisma's own datasource block, which has
// both url and directUrl). Pointed at DIRECT_URL (session mode, port
// 5432) rather than DATABASE_URL: the pooled/pgbouncer URL made the
// schema-engine's can-connect preflight check hang indefinitely against
// Supabase's transaction-mode pooler — confirmed the pooler itself works
// fine via raw psql, so this was specific to how the engine's preflight
// query interacts with pgbouncer, not a real connectivity problem.
//
// Read straight off process.env instead of prisma/config's env() helper:
// that helper throws when the variable is unset, which broke `prisma
// generate` on build machines that have no database credentials — and
// generate needs no connection at all, only the schema. Commands that do
// need a connection (migrate, studio) still fail loudly on their own when
// this resolves to an empty string.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DIRECT_URL ?? process.env.DATABASE_URL ?? "",
  },
});
