
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js reads .env.local; plain `dotenv/config` only reads .env — so a team
// that follows the Next convention puts DATABASE_URL somewhere the Prisma CLI
// never looks, and `prisma migrate deploy` fails with "Environment variable not
// found" while the app itself works fine. Confusing enough that it cost us an
// hour the day before the pitch.
//
// Load .env.local first: dotenv does not overwrite variables that are already
// set, so the file listed first wins — same precedence Next.js uses.
loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });

// datasource.url here is required by prisma.config.ts (removing it entirely
// breaks the CLI), but this config only supports a single URL — no
// directUrl. It's used for the schema-engine's own preflight/CLI
// operations (migrate, studio), not by the app's actual Prisma Client at
// runtime (that reads schema.prisma's own datasource block, which has
// both url and directUrl). Pointed at DIRECT_URL (session mode, port
// 5432) rather than DATABASE_URL: the pooled/pgbouncer URL made the
// schema-engine's can-connect preflight check hang indefinitely against
// Supabase's transaction-mode pooler — confirmed the pooler itself works
// fine via raw psql, so this was specific to how the engine's preflight
// query interacts with pgbouncer, not a real connectivity problem.
//
// Read straight off process.env instead of prisma/config's env() helper:
// that helper throws when the variable is unset, which broke `prisma
// generate` on build machines that have no database credentials — and
// generate needs no connection at all, only the schema. Commands that do
// need a connection (migrate, studio) still fail loudly on their own when
// this resolves to an empty string.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DIRECT_URL ?? process.env.DATABASE_URL ?? "",
  },
});
