
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// datasource.url here is required by prisma.config.ts (removing it entirely
// breaks the CLI), but this config only supports a single URL — no
// directUrl. It's used for the schema-engine's own preflight/CLI
// operations (migrate, studio), not by the app's actual Prisma Client at
// runtime (that reads schema.prisma's own datasource block, which has
// both url and directUrl). Pointed at DIRECT_URL (session mode, port
// 5432) rather than DATABASE_URL: the pooled/pgbouncer URL made the
// schema-engine's can-connect preflight check hang indefinitely against
// Supabase's transaction-mode pooler — confirmed the pooler itself works
// fine via raw psql, so this was specific to how the engine's preflight
// query interacts with pgbouncer, not a real connectivity problem.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DIRECT_URL"),
  },
});
